# Django 自动生成的初始迁移。 / Generated by Django 5.2.17 on 2026-09-09 18:19 UTC.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submit_token', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('process', '正式流程'), ('tutorial', '实践教程'), ('case', '成败案例'), ('handover', '岗位经验')], max_length=20)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=300)),
                ('applicability', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('rejected', '已退回'), ('withdrawn', '已下架')], default='pending', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('review_reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('resubmit', '修改重提'), ('approve', '审核通过'), ('reject', '退回修改'), ('withdraw', '下架')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='knowledge.entry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=300)),
                ('applicability', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='knowledge.entry')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'number'), name='unique_entry_revision')],
            },
        ),
    ]
