# Django 自动生成的活动初始迁移。 / Generated by Django 5.2.17 on 2026-09-10 15:36 UTC.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('activity', '活动'), ('project', '项目')], default='activity', max_length=20)),
                ('objective', models.TextField(max_length=3000)),
                ('audience', models.CharField(max_length=300)),
                ('scheduled_at', models.DateTimeField()),
                ('constraints', models.TextField(max_length=3000)),
                ('plan', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='campus_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('objective', models.TextField(max_length=3000)),
                ('deliverable', models.TextField(max_length=3000)),
                ('acceptance', models.TextField(max_length=3000)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '待认领'), ('waiting', '待接受'), ('active', '进行中'), ('cancelled', '已取消')], default='open', max_length=20)),
                ('blocked_reason', models.CharField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='activities.activity')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.entry')),
            ],
            options={
                'ordering': ['due_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('publish', '发布任务'), ('claim', '主动认领'), ('accept', '接受任务'), ('decline', '暂不接受'), ('block', '报告受阻'), ('unblock', '解除受阻'), ('cancel', '取消任务')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='activities.task')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'open'), _negated=True), ('assignee__isnull', True), _connector='OR'), name='open_task_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['waiting', 'active']), _negated=True), ('assignee__isnull', False), _connector='OR'), name='accepted_task_assigned'),
        ),
    ]
