# Django 自动生成的成果验收迁移。 / Generated by Django 5.2.17 on 2026-09-10 15:58 UTC.

import activities.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '验收通过'), ('return', '退回修改'), ('revoke', '撤销验收')], max_length=20)),
                ('reason', models.CharField(max_length=1000)),
                ('practice', models.BooleanField(default=False)),
                ('contribution', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.BooleanField(default=False)),
                ('contribution', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(unique=True)),
                ('number', models.PositiveIntegerField()),
                ('summary', models.TextField(max_length=3000)),
                ('result_text', models.TextField(blank=True, max_length=20000)),
                ('result_url', models.URLField(blank=True, max_length=2000)),
                ('method', models.TextField(max_length=3000)),
                ('contribution', models.TextField(max_length=3000)),
                ('attachment', models.FileField(blank=True, upload_to=activities.models.delivery_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '待验收'), ('approved', '已验收'), ('returned', '已退回'), ('superseded', '已由新版替代'), ('revoked', '验收已撤销'), ('cancelled', '任务已取消')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='accepted_task_assigned',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '待认领'), ('waiting', '待接受'), ('active', '进行中'), ('review', '待验收'), ('changes', '需修改'), ('done', '已完成'), ('cancelled', '已取消')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='action',
            field=models.CharField(choices=[('publish', '发布任务'), ('claim', '主动认领'), ('accept', '接受任务'), ('decline', '暂不接受'), ('block', '报告受阻'), ('unblock', '解除受阻'), ('cancel', '取消任务'), ('submit', '提交成果'), ('approve', '验收通过'), ('return', '成果退回'), ('revoke', '撤销验收')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['waiting', 'active', 'review', 'changes', 'done']), _negated=True), ('assignee__isnull', False), _connector='OR'), name='accepted_task_assigned'),
        ),
        migrations.AddField(
            model_name='acceptanceevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='achievement', to='activities.task'),
        ),
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='activities.task'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='activities.submission'),
        ),
        migrations.AddField(
            model_name='acceptanceevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='activities.submission'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('task', 'number'), name='unique_task_submission'),
        ),
    ]
