# Django 自动生成的复盘与来源关联迁移。 / Generated by Django 5.2.17 on 2026-09-10 16:26 UTC.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_acceptanceevent_achievement_submission_and_more'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stage',
            field=models.CharField(choices=[('planning', '筹备中'), ('active', '执行中'), ('wrapup', '收尾中'), ('archived', '已归档')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='stage_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ActivityStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=20)),
                ('after', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='activities.activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('superseded', '已由新版替代'), ('withdrawn', '已撤回')], default='draft', max_length=20)),
                ('facts', models.TextField(blank=True, max_length=5000)),
                ('differences', models.TextField(blank=True, max_length=5000)),
                ('hypotheses', models.TextField(blank=True, max_length=5000)),
                ('improvements', models.TextField(blank=True, max_length=5000)),
                ('applicability', models.TextField(blank=True, max_length=3000)),
                ('snapshot', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrospectives', to='activities.activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='RetroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建草稿'), ('save', '保存草稿'), ('refresh', '刷新事实快照'), ('confirm', '确认复盘'), ('withdraw', '撤回复盘'), ('export', '送知识审核')], max_length=20)),
                ('revision', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='activities.retrospective')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDerivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='derivation', to='knowledge.entry')),
                ('retrospective', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_card', to='activities.retrospective')),
            ],
        ),
        migrations.AddConstraint(
            model_name='retrospective',
            constraint=models.UniqueConstraint(fields=('activity', 'number'), name='unique_activity_retro_number'),
        ),
        migrations.AddConstraint(
            model_name='retrospective',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('activity',), name='one_draft_retro_per_activity'),
        ),
    ]
