# 轻量活动档案字段。 / Generated by Django 5.2.17 on 2026-09-22 10:29 UTC.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_stage_activity_stage_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='activity',
            name='event_status',
            field=models.CharField(choices=[('unknown', '待确认'), ('planned', '计划活动'), ('held', '已举行')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='recorded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
