from django.urls import path
from . import views
from . import handoff_views
from . import briefing_views
urlpatterns = [
    path("handoffs/<uuid:pk>/briefing/", briefing_views.page, name="briefing"),
    path("handoffs/<uuid:pk>/briefing/start/", briefing_views.start, name="briefing_start"),
    path("handoffs/<uuid:pk>/briefing/<uuid:sid>/", briefing_views.state, name="briefing_state"),
    path("handoffs/<uuid:pk>/briefing/<uuid:sid>/turns/", briefing_views.turn, name="briefing_turn"),
    path("handoffs/<uuid:pk>/briefing/<uuid:sid>/selection/", briefing_views.selection, name="briefing_selection"),
    path("handoffs/<uuid:pk>/briefing/<uuid:sid>/reset/", briefing_views.reset, name="briefing_reset"),
    path("handoffs/<uuid:pk>/briefing/<uuid:sid>/export/<str:format>/", briefing_views.export, name="briefing_export"),
    path("events/<uuid:event_id>/handoffs/new/", handoff_views.start, name="handoff_start"),
    path("events/<uuid:event_id>/handoffs/permission/", handoff_views.permission, name="handoff_permission"),
    path("handoffs/<uuid:pk>/", handoff_views.detail, name="handoff_detail"),
    path("handoffs/<uuid:pk>/prepare/", handoff_views.prepare, name="handoff_prepare"),
    path("handoffs/<uuid:pk>/items/<uuid:item_id>/", handoff_views.item_save, name="handoff_item_save"),
    path("handoffs/<uuid:pk>/confirm/", handoff_views.confirm, name="handoff_confirm"),
    path("handoffs/<uuid:pk>/copy/", handoff_views.duplicate, name="handoff_copy"),
    path("handoffs/<uuid:pk>/cancel/", handoff_views.cancel, name="handoff_cancel"),
    path("handoffs/<uuid:pk>/export/<str:format>/", handoff_views.export, name="handoff_export"),
    path("",views.home,name="ops_home"),
    path("events/",views.events,name="ops_events"),
    path("events/<uuid:pk>/",views.event,name="ops_event"),
    path("events/<uuid:pk>/permission/",views.permission,name="ops_permission"),
    path("events/<uuid:pk>/revoke-permission/",views.revoke_permission,name="ops_revoke_permission"),
    path("import/",views.upload,name="ops_upload"),
    path("imports/<uuid:pk>/",views.batch,name="ops_batch"),
    path("materials/<uuid:pk>/",views.material,name="ops_material"),
    path("materials/<uuid:pk>/download/",views.download,name="ops_download"),
    path("materials/<uuid:pk>/preview/",views.preview,name="ops_preview"),
    path("materials/<uuid:pk>/action/",views.material_action,name="ops_material_action"),
    path("materials/<uuid:pk>/move/",views.move_material,name="ops_move_material"),
    path("materials/<uuid:pk>/records/",views.import_records,name="ops_import_records"),
    path("members/",views.members,name="ops_members"),
    path("members/new/",views.person_edit,name="ops_person_new"),
    path("members/compare/",views.compare,name="ops_compare"),
    path("members/<uuid:pk>/",views.member,name="ops_member"),
    path("members/<uuid:pk>/edit/",views.person_edit,name="ops_person_edit"),
    path("roster/",views.roster,name="ops_roster"),
    path("roster/template/",views.roster_template,name="ops_roster_template"),
    path("observations/new/",views.evidence_edit,name="ops_evidence_new"),
    path("observations/<uuid:pk>/edit/",views.evidence_edit,name="ops_evidence_edit"),
    path("observations/<uuid:pk>/merge/",views.merge,name="ops_merge"),
    path("analysis/",views.assistant,name="ops_assistant"),
    path("analysis/<uuid:pk>/",views.analysis_detail,name="ops_analysis"),
    path("analysis/<uuid:pk>/cancel/",views.cancel_analysis,name="ops_cancel_analysis"),
    path("analysis/<uuid:pk>/citation/<int:item>/<int:reference>/",views.citation,name="ops_citation"),
    path("settings/",views.settings_view,name="ops_settings"),
]
