# 负责人运营台初始迁移。 / Generated by Django 5.2.17 on 2026-09-22 10:29 UTC.

import django.db.models.deletion
import operations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0004_activity_description_activity_event_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('disabled', '未启用'), ('local', '本机模型'), ('cloud', '云端模型')], default='disabled', max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, max_length=500)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('is_roster', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_fingerprint', models.CharField(max_length=64)),
                ('material_ids', models.JSONField(default=list)),
                ('auto_future', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=operations.models.archive_path)),
                ('original_name', models.CharField(max_length=255)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('parsed', '已提取正文'), ('unsupported', '仅归档'), ('failed', '解析失败')], default='pending', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('segments', models.JSONField(default=list)),
                ('tables', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('excluded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.importbatch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='activities.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='operations.material')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='operations.person')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('participation', '参与'), ('delivery', '交付'), ('help', '协作帮助'), ('initiative', '主动推进'), ('communication', '沟通记录')], max_length=20)),
                ('confidence', models.CharField(choices=[('verified', '负责人核实'), ('self_report', '材料自述'), ('candidate', '待核验线索')], default='candidate', max_length=20)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('anchor', models.CharField(blank=True, max_length=100)),
                ('quote', models.TextField(max_length=3000)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.evidence')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='activities.activity')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.material')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='operations.person')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('running', '分析中'), ('complete', '已完成'), ('failed', '分析失败'), ('stale', '来源已变化'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('config_fingerprint', models.CharField(max_length=64)),
                ('sources', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='activities.activity')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='operations.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='operations.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('event', 'sha256'), name='event_material_hash_unique'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('member', 'material'), name='material_member_mention_unique'),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('member', 'value'), name='member_alias_unique'),
        ),
    ]
