# 分析日期范围。 / Generated by Django 5.2.17 on 2026-09-22 11:34 UTC.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_material_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
