# 资料归属更正版本。 / Generated by Django 5.2.17 on 2026-09-22 11:41 UTC.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_analysisrun_end_date_analysisrun_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
