# Django生成的新增准备会话迁移。 / Preparation-session migration generated by Django 5.2.17.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_local_gateway_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.JSONField(default=dict)),
                ('turns', models.JSONField(default=list)),
                ('selected', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('pending', models.UUIDField(blank=True, null=True)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefings', to='operations.handoffpack')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
